import { useState } from "react";
import type { FormEvent } from "react";
import { queryTasksWithAI } from "../api/api";
import type { AiTaskQueryResponse } from "../api/api";

type Props = { onClose: () => void };
const examples = ["Which tasks assigned to Mouser are overdue?", "Show me all tasks with more than 2 delays.", "Summarize why the dashboard task got delayed."];

export default function AiAssistantModal({ onClose }: Props) {
  const [question, setQuestion] = useState("");
  const [result, setResult] = useState<AiTaskQueryResponse | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!question.trim() || loading) return; setLoading(true); setError(""); setResult(null); try { setResult(await queryTasksWithAI(question.trim())); } catch (err: any) { setError(err?.response?.data?.message || "Unable to process the task question"); } finally { setLoading(false); } };
  const tasks = result?.tasks || (result?.task ? [result.task] : []);
  const resultContent = tasks.length > 0 ? <div className="space-y-2">{tasks.map((task, index) => <div key={task.id ?? index} className="rounded-lg border border-slate-200 bg-white p-3"><div className="flex items-start justify-between gap-3"><p className="font-medium text-slate-800">{task.title || "Untitled task"}</p>{task.status && <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">{task.status}</span>}</div>{task.assignee_name && <p className="mt-1 text-xs text-slate-500">Assigned to {task.assignee_name}</p>}{task.delay_count !== undefined && <p className="mt-1 text-xs text-slate-500">Delays: {task.delay_count}</p>}{task.description && <p className="mt-2 text-xs text-slate-600">{task.description}</p>}</div>)}</div> : result?.summary || result?.message ? <p className="whitespace-pre-wrap">{result.summary || result.message}</p> : result?.count !== undefined ? <p>Found {result.count} matching task{result.count === 1 ? "" : "s"}.</p> : <p>No matching task data was returned.</p>;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/30 p-4" onMouseDown={onClose}><div className="w-full max-w-xl rounded-xl bg-white p-5 shadow-xl" onMouseDown={(event) => event.stopPropagation()}><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold text-slate-800">AI Assistant</h2><button type="button" onClick={onClose} className="text-xl leading-none text-slate-400 hover:text-slate-700">×</button></div><form onSubmit={submit}><textarea value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask anything about your tasks or users..." className="min-h-24 w-full resize-y rounded-lg border border-slate-200 p-3 text-sm outline-none focus:border-violet-400" /><div className="mt-1 flex flex-wrap items-center gap-x-1 gap-y-0 leading-4"><span className="text-[11px] text-slate-400">Try asking:</span>{examples.map((example, index) => <span key={example} className="inline"><button type="button" onClick={() => setQuestion(example)} className="p-0 text-left text-[11px] text-slate-500 transition hover:text-violet-700">{example}</button>{index < examples.length - 1 && <span className="text-[11px] text-slate-300">, </span>}</span>)}</div><div className="mt-3 flex justify-end"><button type="submit" disabled={loading || !question.trim()} className="rounded-lg bg-violet-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-violet-700 disabled:opacity-50">{loading ? "Asking..." : "Ask AI"}</button></div></form>{error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-600">{error}</p>}{result && <div className="mt-4 max-h-72 overflow-auto rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{resultContent}</div>}</div></div>;
}

